### ISSUE TITLE
How to prevent NAN influence values?

### ISSUE THREAD

**Issue by ajsanjoaquin** [nimarb/pytorch_influence_functions#27]
I am consistently getting NAN values in my output on CIFAR-10 data for recursion depths (r-depth) as low as 15. I noticed that the influence values for r-depth = 1 are big negative values (e.x. -2000) and they just explode  to -1e36 for r-depth = 10.
I increased the scale value to 500 as suggested in #6, but to no avail. I have also used the default r-depth = 5000. I am using the function ```calc_influence_single```. The averaging value (r) is 1 for all of these as suggested by #2.

Does anyone have advice or solution to this? Thank you.

**Comment by fjzpcmj** [comment]
@ajsanjoaquin  hello，do you solve nan problem?  and how to solve it? I met this problem too.

**Comment by ajsanjoaquin** [comment]
@fjzpcmj Yes my [current fork](https://github.com/ajsanjoaquin/pytorch_influence_functions) works for this.

Here's my config file. Feel free to edit. Recursion depth and r_averaging are based on a post in the issues section, but I'm forgetting which. This works for CIFAR-10. Also, do not worry about the est_norm being very big or small during calculation.

```
config = {
        'outdir': <OUTPUT_DIR>,
        'seed': 42,
        'gpu': 0,
        'num_classes': 10,
        'test_sample_num': False,
        'test_start_index': 0,
        'recursion_depth': 5,
        'r_averaging': 10,
        'scale':50000,
        'damp': 0.01,
        'calc_method': 'img_wise'
    }
```

**Comment by fjzpcmj** [comment]
@ajsanjoaquin Thanks for reply.  Since your new fork modify original code much,  DO you remember which part can fix  the 'nan problem'.  I read the all issues, in the #6  ,  i found the scale should be large.  [issue#6](https://github.com/nimarb/pytorch_influence_functions/issues/6#issuecomment-654014496). Is the scale most important to fix the nan problem?
