### ISSUE TITLE
Overwriting h_estimate rather than updating it

### ISSUE THREAD

**Issue by andrewsilva9** [nimarb/pytorch_influence_functions#4]
Referring to this line in this repo:  https://github.com/nimarb/pytorch_influence_functions/blob/a6f34f6c85160e9c285d81ce79c2b6cbf9bd3dab/pytorch_influence_functions/influence_function.py#L49

The implementation of this line from the TF repo: https://github.com/kohpangwei/influence-release/blob/578bc458b4d7cc39ed7343b9b271a04b60c782b1/influence/genericNeuralNet.py#L500
which is  `cur_estimate = [a + (1-damping) * b - c/scale for (a,b,c) in zip(v, cur_estimate, hessian_vector_val)]`  seems to be incorrect. 

Rather than using the current estimate in conjunction with the new vector product, the implementation in this repo is using the original estimation over and over.

I believe the fix would be to simply set `h_estimate = v.copy()` higher up in the function, remove `h_init_estimates` entirely, and use `h_estimate` in the for loop, like this:
`h_estimate = [ _v + (1 - damp) * h_e - _hv / scale for _v, h_e, _hv in zip(v, h_estimate, hv)]`

**Comment by peizhaoli05** [comment]
Agree!

**Comment by nimarb** [comment]
Thanks a lot for bringing this to my attention :)! This actually introduced an error into the estimated H, which changes the outcome with large recursion values.

**Comment by andrewsilva9** [comment]
Yeah sorry my fix was not correct, I was writing from memory. I actually do keep `h_init = v.copy()` and send `h_init` into the `hvp` calculation. So:
`hv = hvp(loss_val, list(model.parameters()), h_init)`

instead of `hv = hvp(loss_val, list(model.parameters()), h_estimates)`. But you can verify whether or not that's correct, I am not certain :\
